<?php declare(strict_types=1);
require __DIR__ . '/AbstractClass.php';
require __DIR__ . '/AbstractTrait.php';
require __DIR__ . '/C.php';
require __DIR__ . '/D.php';
require __DIR__ . '/Dependency.php';
require __DIR__ . '/Observer.php';
require __DIR__ . '/SomeClass.php';
require __DIR__ . '/SomeInterface.php';
require __DIR__ . '/Subject.php';
require __DIR__ . '/X.php';
require __DIR__ . '/Y.php';
require __DIR__ . '/Z.php';
